# Generated by Django 5.0.9 on 2024-11-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaptersLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.TextField()),
                ('error_log', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=25)),
                ('domain_url', models.URLField()),
                ('harvest_type', models.CharField(choices=[('manga', 'Manga'), ('anime', 'Anime'), ('both', 'Both'), ('none', 'None')], default='none', max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangasLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.TextField()),
                ('error_log', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_list', models.TextField(default=dict)),
                ('manga_title', models.CharField(max_length=150)),
                ('manga_genre_list', models.TextField(default=dict)),
                ('manga_genre', models.CharField(max_length=50)),
                ('description_list', models.TextField(default=dict)),
                ('description', models.CharField(max_length=250)),
                ('re_title', models.TextField(default=dict)),
                ('manga_url', models.CharField(max_length=250)),
                ('re_url', models.TextField(default=dict)),
                ('manga_cover_img', models.CharField(max_length=250)),
                ('re_cover_img', models.TextField(default=dict)),
                ('chapter_list', models.TextField(default=list)),
                ('chapter_title', models.CharField(max_length=250)),
                ('re_chapter_title', models.TextField(default=dict)),
                ('chapter_url', models.CharField(max_length=250)),
                ('re_chapter_url', models.TextField(default=dict)),
                ('payload', models.TextField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harvest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvest_routes.harvester')),
            ],
        ),
    ]
